### ISSUE TITLE
Recruitment web app - Initialization

### ISSUE THREAD

**Issue by KhoaNDAHopee** [HopeeSolutionsRuby/demo-app#9]
- Rails 7.x
- Ruby 3.x
- Gems:
  - bootstrap-sass
  - mysql2
  - sass-rails
  - factory_bot_rails
  - faker
  - better_errors
  - binding_of_caller
  - letter_opener
  - rubocop
  - rubocop-rails
 - .rubocop.yml
```
require: 
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'Rakefile'
    - 'config.ru'
    - 'config/**/*'
    - 'bin/**/*'
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/HashSyntax:
  EnforcedShorthandSyntax: never
```
- Push to ``develop``
